# Generated by Django 4.0 on 2022-10-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsm',
            name='time_elapsed_display_value',
            field=models.CharField(help_text='Time elapsed display value', max_length=200, null=True, verbose_name='time_elapsed_display_value'),
        ),
    ]
