# Generated by Django 4.0 on 2022-09-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracter', '0003_siem_soar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsm',
            name='account_id',
            field=models.CharField(help_text='Account id', max_length=5000, null=True, verbose_name='account_id'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='account_name',
            field=models.CharField(help_text='Account name', max_length=5000, null=True, verbose_name='account_name'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='accountcontract_billunclosed',
            field=models.CharField(help_text='Account contract bill unclosed', max_length=5000, null=True, verbose_name='accountcontract_billunclosed'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='accountcontract_contractid',
            field=models.CharField(help_text='Account contract contract id', max_length=5000, null=True, verbose_name='accountcontract_contractid'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='accountcontract_contractname',
            field=models.CharField(help_text='Account contract contract name', max_length=5000, null=True, verbose_name='accountcontract_contractname'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='accountcontract_contractnumber',
            field=models.CharField(help_text='Account contract contract number', max_length=5000, null=True, verbose_name='accountcontract_contractnumber'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='accountcontract_description',
            field=models.CharField(help_text='Account contract description', max_length=5000, null=True, verbose_name='accountcontract_description'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='accountcontract_isactivecontract',
            field=models.CharField(help_text='Account contract is active contract', max_length=5000, null=True, verbose_name='accountcontract_isactivecontract'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='accountcontract_serviceplan_id',
            field=models.CharField(help_text='Account contract serviceplan id', max_length=5000, null=True, verbose_name='accountcontract_serviceplan_id'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='approval_status',
            field=models.CharField(help_text='Approva Status', max_length=5000, null=True, verbose_name='approval_status'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='assets',
            field=models.CharField(help_text='Assets', max_length=5000, null=True, verbose_name='assets'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='assigned_time_display_value',
            field=models.CharField(help_text='Assigned time display value', max_length=5000, null=True, verbose_name='assigned_time_display_value'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='assigned_time_value',
            field=models.CharField(help_text='Assigned time value', max_length=5000, null=True, verbose_name='assigned_time_value'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='billing_status_billingstatusid',
            field=models.CharField(help_text='Billing status billingstatusid', max_length=5000, null=True, verbose_name='billing_status_billingstatusid'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='billing_status_billingstatusname',
            field=models.CharField(help_text='Billing Status Billing Status Name', max_length=5000, null=True, verbose_name='billing_status_billingstatusname'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='callback_url',
            field=models.CharField(help_text='Callback url', max_length=5000, null=True, verbose_name='callback_url'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='category_id',
            field=models.CharField(help_text='Category id', max_length=5000, null=True, verbose_name='category_id'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='category_name',
            field=models.CharField(help_text='Category name', max_length=5000, null=True, verbose_name='category_name'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='closure_info_closure_code',
            field=models.CharField(help_text='Closure info closure code', max_length=5000, null=True, verbose_name='closure_info_closure_code'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='closure_info_closure_code_id',
            field=models.CharField(help_text='Closure info closure code id', max_length=5000, null=True, verbose_name='closure_info_closure_code_id'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='closure_info_closure_code_name',
            field=models.CharField(help_text='Closure info closure code name', max_length=5000, null=True, verbose_name='closure_info_closure_code_name'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='closure_info_closure_comments',
            field=models.CharField(help_text='Closure info closure comments', max_length=5000, null=True, verbose_name='closure_info_closure_comments'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='closure_info_requester_ack_comments',
            field=models.CharField(help_text='Closure info requester ack comments', max_length=5000, null=True, verbose_name='closure_info_requester_ack_comments'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='closure_info_requester_ack_resolution',
            field=models.CharField(help_text='Closure info requester ack resolution', max_length=5000, null=True, verbose_name='closure_info_requester_ack_resolution'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='closure_info_signoff',
            field=models.CharField(help_text='Closure info signoff', max_length=5000, null=True, verbose_name='closure_info_signoff'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='completed_time_display_value',
            field=models.CharField(help_text='Completed time display value', max_length=5000, null=True, verbose_name='completed_time_display_value'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='completed_time_value',
            field=models.CharField(help_text='Completed time value', max_length=5000, null=True, verbose_name='completed_time_value'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='created_by_email_id',
            field=models.CharField(help_text='Created By Email Id', max_length=5000, null=True, verbose_name='created_by_email_id'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='created_by_id',
            field=models.CharField(help_text='Created By id', max_length=5000, null=True, verbose_name='created_by_id'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='created_by_is_vipuser',
            field=models.CharField(help_text='Created By is vipuser', max_length=5000, null=True, verbose_name='created_by_is_vipuser'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='created_by_mobile',
            field=models.CharField(help_text='Created by Mobile', max_length=5000, null=True, verbose_name='created_by_mobile'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='created_by_name',
            field=models.CharField(help_text='Created By Name', max_length=5000, null=True, verbose_name='created_by_name'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='created_by_status',
            field=models.CharField(help_text='Created by status', max_length=5000, null=True, verbose_name='created_by_status'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='created_time_display_value',
            field=models.CharField(help_text='Created time display value', max_length=5000, null=True, verbose_name='created_time_display_value'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='created_time_value',
            field=models.CharField(help_text='Created time Value', max_length=5000, null=True, verbose_name='created_time_value'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='department_id',
            field=models.CharField(help_text='Department ID', max_length=5000, null=True, verbose_name='department_id'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='department_name',
            field=models.CharField(help_text='Department name', max_length=5000, null=True, verbose_name='department_name'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='description',
            field=models.CharField(help_text='Description', max_length=5000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='due_by_time',
            field=models.CharField(help_text='Due by time', max_length=5000, null=True, verbose_name='due_by_time'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='email_cc',
            field=models.CharField(help_text='Email cc', max_length=5000, null=True, verbose_name='email_cc'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='email_ids_to_notify',
            field=models.CharField(help_text='Email ids to notify', max_length=5000, null=True, verbose_name='email_ids_to_notify'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='email_to',
            field=models.CharField(help_text='Requester ID', max_length=5000, null=True, verbose_name='email_to'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='first_response_due_by_time_display_value',
            field=models.CharField(help_text='First response due by time', max_length=5000, null=True, verbose_name='first_response_due_by_time_display_value'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='first_response_due_by_time_value',
            field=models.CharField(help_text='First response due by time value', max_length=5000, null=True, verbose_name='first_response_due_by_time_value'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='group_id',
            field=models.CharField(help_text='Group Id', max_length=5000, null=True, verbose_name='group_id'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='group_name',
            field=models.CharField(help_text='Group Name', max_length=5000, null=True, verbose_name='group_name'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='has_attachments',
            field=models.CharField(help_text='Has attachments', max_length=5000, null=True, verbose_name='has_attachments'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='has_conversation',
            field=models.CharField(help_text='Has conversation', max_length=5000, null=True, verbose_name='has_conversation'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='has_dependency',
            field=models.CharField(help_text='Has Dependency', max_length=5000, null=True, verbose_name='has_dependency'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='has_draft',
            field=models.CharField(help_text='Has draft', max_length=5000, null=True, verbose_name='has_draft'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='has_linked_requests',
            field=models.CharField(help_text='Has linked requests', max_length=5000, null=True, verbose_name='has_linked_requests'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='has_notes',
            field=models.CharField(help_text='Has notes', max_length=5000, null=True, verbose_name='has_notes'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='has_problem',
            field=models.CharField(help_text='Has Problem', max_length=5000, null=True, verbose_name='has_problem'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='has_project',
            field=models.CharField(help_text='Has Project', max_length=5000, null=True, verbose_name='has_project'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='has_request_initiated_change',
            field=models.CharField(help_text='Has request initiated change', max_length=5000, null=True, verbose_name='has_request_initiated_change'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='has_resolution_attachments',
            field=models.CharField(help_text='Resolution Attachments', max_length=5000, null=True, verbose_name='has_resolution_attachments'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='impact_details',
            field=models.CharField(help_text='Impact Details', max_length=5000, null=True, verbose_name='impact_details'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='impact_id',
            field=models.CharField(help_text='Impact Id', max_length=5000, null=True, verbose_name='impact_id'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='impact_name',
            field=models.CharField(help_text='Impact Name', max_length=5000, null=True, verbose_name='impact_name'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='is_billable',
            field=models.CharField(help_text='Is billable', max_length=5000, null=True, verbose_name='is_billable'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='is_fcr',
            field=models.CharField(help_text='Is fcr', max_length=5000, null=True, verbose_name='is_fcr'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='is_first_response_overdue',
            field=models.CharField(help_text='Is first response overdue', max_length=5000, null=True, verbose_name='is_first_response_overdue'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='is_overdue',
            field=models.CharField(help_text='Is overdue', max_length=5000, null=True, verbose_name='is_overdue'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='is_reopened',
            field=models.CharField(help_text='Is reopenend', max_length=5000, null=True, verbose_name='is_reopened'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='is_request_contract_applicable',
            field=models.CharField(help_text='Request contrat applicable', max_length=5000, null=True, verbose_name='is_request_contract_applicable'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='is_service_request',
            field=models.CharField(help_text='Is service Request', max_length=5000, null=True, verbose_name='is_service_request'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='is_shared',
            field=models.CharField(help_text='Is shared', max_length=5000, null=True, verbose_name='is_shared'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='is_trashed',
            field=models.CharField(help_text='Is trashed', max_length=5000, null=True, verbose_name='is_trashed'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='item',
            field=models.CharField(help_text='Item', max_length=5000, null=True, verbose_name='item'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='itsm_id',
            field=models.CharField(help_text='Id', max_length=5000, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='last_updated_time_display_value',
            field=models.CharField(help_text='Last updated time', max_length=5000, null=True, verbose_name='last_updated_time_display_value'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='last_updated_time_value',
            field=models.CharField(help_text='Last updated time value', max_length=5000, null=True, verbose_name='last_updated_time_value'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='level_id',
            field=models.CharField(help_text='Level id', max_length=5000, null=True, verbose_name='level_id'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='level_name',
            field=models.CharField(help_text='Level Name', max_length=5000, null=True, verbose_name='level_name'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='lifecycle',
            field=models.CharField(help_text='Lifecycle', max_length=5000, null=True, verbose_name='lifecycle'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='linked_to_request',
            field=models.CharField(help_text='Linked Request', max_length=5000, null=True, verbose_name='linked_to_request'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='mode',
            field=models.CharField(help_text='Mode', max_length=5000, null=True, verbose_name='mode'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='mode_id',
            field=models.CharField(help_text='Mode id', max_length=5000, null=True, verbose_name='mode_id'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='mode_name',
            field=models.CharField(help_text='Mode name', max_length=5000, null=True, verbose_name='mode_name'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='priority_color',
            field=models.CharField(help_text='Priority color', max_length=5000, null=True, verbose_name='priority_color'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='priority_id',
            field=models.CharField(help_text='Priority Id', max_length=5000, null=True, verbose_name='priority_id'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='priority_name',
            field=models.CharField(help_text='Priority Name', max_length=5000, null=True, verbose_name='priority_name'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='request_template_task_ids',
            field=models.CharField(help_text='Request template task ids', max_length=5000, null=True, verbose_name='request_template_task_ids'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='request_type_id',
            field=models.CharField(help_text='Request type id', max_length=5000, null=True, verbose_name='request_type_id'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='request_type_name',
            field=models.CharField(help_text='Request type name', max_length=5000, null=True, verbose_name='request_type_name'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='requester_email_id',
            field=models.CharField(help_text='Requester Email Id', max_length=5000, null=True, verbose_name='requester_email_id'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='requester_id',
            field=models.CharField(help_text='Requester ID', max_length=5000, null=True, verbose_name='requester_id'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='requester_is_vipuser',
            field=models.CharField(help_text='Requester vipuser', max_length=5000, null=True, verbose_name='requester_is_vipuser'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='requester_mobile',
            field=models.CharField(help_text='Requester Mobile', max_length=5000, null=True, verbose_name='requester_mobile'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='requester_name',
            field=models.CharField(help_text='Requester name', max_length=5000, null=True, verbose_name='requester_name'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='requester_status',
            field=models.CharField(help_text='Requester Status', max_length=5000, null=True, verbose_name='requester_status'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='resolution_content',
            field=models.CharField(help_text='Resolution Content', max_length=5000, null=True, verbose_name='resolution_content'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='resolution_resolution_attachments',
            field=models.CharField(help_text='Resolution on Attachment', max_length=5000, null=True, verbose_name='resolution_resolution_attachments'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='resolution_submitted_by_email_id',
            field=models.CharField(help_text='Resolution on Email id', max_length=5000, null=True, verbose_name='resolution_submitted_by_email_id'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='resolution_submitted_by_id',
            field=models.CharField(help_text='Resolution by id', max_length=5000, null=True, verbose_name='resolution_submitted_by_id'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='resolution_submitted_by_is_vipuser',
            field=models.CharField(help_text='Resolution on vipuser', max_length=5000, null=True, verbose_name='resolution_submitted_by_is_vipuser'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='resolution_submitted_by_mobile',
            field=models.CharField(help_text='Resolution on Mobile', max_length=5000, null=True, verbose_name='resolution_submitted_by_mobile'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='resolution_submitted_by_name',
            field=models.CharField(help_text='Resolution on name', max_length=5000, null=True, verbose_name='resolution_submitted_by_name'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='resolution_submitted_by_status',
            field=models.CharField(help_text='Resolution on Status', max_length=5000, null=True, verbose_name='resolution_submitted_by_status'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='resolution_submitted_on_display_value',
            field=models.CharField(help_text='Resolution on display value', max_length=5000, null=True, verbose_name='resolution_submitted_on_display_value'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='resolution_submitted_on_value',
            field=models.CharField(help_text='Resolution on value', max_length=5000, null=True, verbose_name='resolution_submitted_on_value'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='resolved_time_display_value',
            field=models.CharField(help_text='Resolved time display value', max_length=5000, null=True, verbose_name='resolved_time_display_value'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='resolved_time_value',
            field=models.CharField(help_text='Resolved time value', max_length=5000, null=True, verbose_name='resolved_time_value'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='service_category_id',
            field=models.CharField(help_text='Service Category Id', max_length=5000, null=True, verbose_name='service_category_id'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='service_category_name',
            field=models.CharField(help_text='Service Category Name', max_length=5000, null=True, verbose_name='service_category_name'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='site_id',
            field=models.CharField(help_text='Site ID', max_length=5000, null=True, verbose_name='site_id'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='site_name',
            field=models.CharField(help_text='Site Name', max_length=5000, null=True, verbose_name='site_name'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='sla_id',
            field=models.CharField(help_text='SLA Id', max_length=5000, null=True, verbose_name='sla_id'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='sla_name',
            field=models.CharField(help_text='SLA Name', max_length=5000, null=True, verbose_name='sla_name'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='status_color',
            field=models.CharField(help_text='Status Color', max_length=5000, null=True, verbose_name='status_color'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='status_id',
            field=models.CharField(help_text='Status id', max_length=5000, null=True, verbose_name='status_id'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='status_name',
            field=models.CharField(help_text='Status name', max_length=5000, null=True, verbose_name='status_name'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='subcategory',
            field=models.CharField(help_text='Subcategory', max_length=5000, null=True, verbose_name='subcategory'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='subcategory_id',
            field=models.CharField(help_text='Subcategory id', max_length=5000, null=True, verbose_name='subcategory_id'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='subcategory_name',
            field=models.CharField(help_text='Subcategory name', max_length=5000, null=True, verbose_name='subcategory_name'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='subject',
            field=models.CharField(help_text='Subject', max_length=5000, null=True, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='technician_email_id',
            field=models.CharField(help_text='Technician Email ID', max_length=5000, null=True, verbose_name='technician_email_id'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='technician_id',
            field=models.CharField(help_text='Technician id', max_length=5000, null=True, verbose_name='technician_id'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='technician_mobile',
            field=models.CharField(help_text='Technician Mobile', max_length=5000, null=True, verbose_name='technician_mobile'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='technician_name',
            field=models.CharField(help_text='Technician name', max_length=5000, null=True, verbose_name='technician_name'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='technician_status',
            field=models.CharField(help_text='Technician Status', max_length=5000, null=True, verbose_name='technician_status'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='template_id',
            field=models.CharField(help_text='Template id', max_length=5000, null=True, verbose_name='template_id'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='template_name',
            field=models.CharField(help_text='Template name', max_length=5000, null=True, verbose_name='template_name'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='time_elapsed_display_value',
            field=models.CharField(help_text='Time elapsed display value', max_length=5000, null=True, verbose_name='time_elapsed_display_value'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='time_elapsed_value',
            field=models.CharField(help_text='Time elapsed value', max_length=5000, null=True, verbose_name='time_elapsed_value'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='udf_fields_udf_long_3302',
            field=models.CharField(help_text='UDF Fields udf sline 3302', max_length=5000, null=True, verbose_name='udf_fields_udf_long_3302'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='udf_fields_udf_long_4502',
            field=models.CharField(help_text='Udf fields udf long 4502', max_length=5000, null=True, verbose_name='udf_fields_udf_long_4502'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='udf_fields_udf_sline_4501',
            field=models.CharField(help_text='Udf fields', max_length=5000, null=True, verbose_name='udf_fields_udf_sline_4501'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='udf_fields_udf_sline_5401',
            field=models.CharField(help_text='UDF Fields udf sline 5401', max_length=5000, null=True, verbose_name='udf_fields_udf_sline_5401'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='urgency_id',
            field=models.CharField(help_text='Urgency Id', max_length=5000, null=True, verbose_name='urgency_id'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='urgency_name',
            field=models.CharField(help_text='Urgency Name', max_length=5000, null=True, verbose_name='urgency_name'),
        ),
    ]
