# Generated by Django 4.0 on 2022-09-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracter', '0004_alter_itsm_account_id_alter_itsm_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soar',
            name='AlertsCount',
            field=models.CharField(help_text='alertscount', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='soar',
            name='AssignedUser',
            field=models.CharField(help_text='Assigned User', max_length=2000, null=True, verbose_name='AssignedUser'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='Case_id',
            field=models.CharField(help_text='Case Id', max_length=2000, null=True, verbose_name='Case_id'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='ClosingTime',
            field=models.CharField(help_text='Closing Time', max_length=2000, null=True, verbose_name='ClosingTime'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='Environment',
            field=models.CharField(help_text='Environment', max_length=2000, null=True, verbose_name='Environment'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='Important',
            field=models.CharField(help_text='Important', max_length=2000, null=True, verbose_name='Important'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='Incident',
            field=models.CharField(help_text='Incident', max_length=2000, null=True, verbose_name='Incident'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='Outcomes',
            field=models.CharField(help_text='Outcomes', max_length=2000, null=True, verbose_name='Outcomes'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='Ports',
            field=models.CharField(help_text='Ports', max_length=2000, null=True, verbose_name='Ports'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='Priority',
            field=models.CharField(help_text='Priority', max_length=2000, null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='Products',
            field=models.CharField(help_text='Product', max_length=2000, null=True, verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='Reason',
            field=models.CharField(help_text='Reason', max_length=2000, null=True, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='RootCause',
            field=models.CharField(help_text='Root Cause', max_length=2000, null=True, verbose_name='RootCause'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='SOAR_ID',
            field=models.CharField(help_text='SOAR Id', max_length=2000, null=True, verbose_name='SOAR_ID'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='Sources',
            field=models.CharField(help_text='Sources', max_length=2000, null=True, verbose_name='Sources'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='Stage',
            field=models.CharField(help_text='Stage', max_length=2000, null=True, verbose_name='Stage'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='Status',
            field=models.CharField(help_text='Status', max_length=2000, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='Suspicious',
            field=models.CharField(help_text='Suspicious', max_length=2000, null=True, verbose_name='Suspicious'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='Tags',
            field=models.CharField(help_text='Tags', max_length=2000, null=True, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='TicketIDs',
            field=models.CharField(help_text='Ticket Ids', max_length=2000, verbose_name='TicketIDs'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='Time',
            field=models.CharField(help_text='Time', max_length=2000, null=True, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='Title',
            field=models.CharField(help_text='Title', max_length=2000, null=True, verbose_name='Title'),
        ),
    ]
