from django.db import models
from django.utils.translation import gettext_lazy as _


class ITSM(models.Model):
    """
    Model to hold data for ITSM data
    """
    class PriorityValue(models.TextChoices):
        Low = "Low", _("Low")
        Medium = "Medium", _("Medium")
        High = "High", _("High")

    class ModeOfRequest(models.TextChoices):
        Email = "Email", _("Email")
        Call = "Call", _("Call")
        Message = "Message", _("Message")
        Whatsapp = "Whatsapp", _("Whatsapp")

    RequestID = models.CharField(max_length=200, null=True, help_text="Request Id")
    Request_mode = models.CharField(max_length=200, choices=ModeOfRequest.choices, null=True, help_text="Request Mode")
    Cluster = models.CharField(max_length=200, null=True, help_text="Cluster")
    Applicant = models.CharField(max_length=200, null=True, help_text="Applicant")
    Department = models.CharField(max_length=200, null=True, help_text="Department")
    Category = models.CharField(max_length=200, null=True, help_text="Category")
    Subcategory = models.CharField(max_length=200, null=True, help_text="Sub Category")
    Article = models.CharField(max_length=200, null=True, help_text="Article")
    Affair = models.CharField(max_length=200, help_text="Affair")
    Created_by = models.CharField(max_length=200, null=True, help_text="Created By")
    Urgency = models.CharField(max_length=200, choices=PriorityValue.choices, null=True, help_text="Urgency")
    Impact = models.CharField(max_length=200, choices=PriorityValue.choices, null=True, help_text="Impact")
    RequestType = models.CharField(max_length=200, null=True, help_text="Request Type")
    Technician = models.CharField(max_length=200, null=True, help_text="Technician")
    Description = models.CharField(max_length=200, null=True, help_text="Description")
    Site = models.CharField(max_length=200, null=True, help_text="Site")
    Region = models.CharField(max_length=200, null=True, help_text="Region")
    Approval_Status = models.CharField(max_length=200, null=True, help_text="Approval Status")
    Request_closing_code = models.CharField(max_length=200, null=True, help_text="Request Closing Code")
    Request_Closure_Comments = models.CharField(max_length=200, null=True, help_text="Request_Closure_Comments")
    ServiceCategory = models.CharField(max_length=200, null=True, help_text="Service Category")
    Priority = models.CharField(max_length=200, choices=PriorityValue.choices, null=True, help_text="Priority")
    Level = models.CharField(max_length=200, null=True, help_text="Level")
    Asset_Name = models.CharField(max_length=200, null=True, help_text="Asset Name")
    Application_Status = models.CharField(max_length=200, null=True, help_text="Application status")
    Pending_status = models.BooleanField(null=True, help_text="Pending Status")
    CreatedTime = models.DateTimeField(max_length=200, null=True, help_text="Created Time")
    Answer_date = models.DateTimeField(max_length=200, null=True, help_text="Answer Date")
    Expiration_time = models.DateTimeField(max_length=200, null=True, help_text="Expiration Time")
    Ending_time = models.DateTimeField(max_length=200, null=True, help_text="Ending Time")
    Time_elapsed = models.DateTimeField(max_length=200, null=True, help_text="Time Elapsed")
    Expired_status = models.BooleanField(null=True, help_text="Expire Status")
    Itsm_id = models.CharField(max_length=200, null=True, help_text="ITSM Id")
    Subject = models.CharField(max_length=200, null=True, help_text="Subject")
    RequestStatus = models.CharField(max_length=200, null=True, help_text="Request Status")
    Account = models.CharField(max_length=200, null=True, help_text="Account")
    Resolution = models.CharField(max_length=200, null=True, help_text="Resolution")
    Reopened = models.BooleanField(null=True, help_text="Reopened")
    RCF = models.BooleanField(null=True, help_text="RCF")
    User_On_Behalf_Of_OBO = models.CharField(max_length=200, null=True, help_text="Subject")
    Total_cost = models.CharField(max_length=200, null=True, help_text="Subject")
    Exchanged_Service = models.CharField(max_length=200, null=True, help_text="Subject")
    Sale_order = models.CharField(max_length=200, null=True, help_text="Subject")
    Number_of_Services = models.IntegerField(null=True, help_text="Subject")
    Solicitant_area = models.CharField(max_length=200, null=True, help_text="Solicitant_area")
    Complexity = models.CharField(max_length=200, null=True, help_text="Complexity")
    Type = models.CharField(max_length=200, null=True, help_text="Type")
    Opportunity_Status = models.CharField(max_length=200, null=True, help_text="Opportunity_Status")
    Qualys_first_time_detected = models.CharField(max_length=200, null=True, help_text="qualys_first_time_detected")
    Qualys_url = models.CharField(max_length=200, null=True, help_text="qualys_url")
    Qualys_last_time_detected = models.CharField(max_length=200, null=True, help_text="Iqualys_last_time_detected")
    Qualys_last_time_tested = models.CharField(max_length=200, null=True, help_text="qualys_last_time_tested")
    Qualys_category = models.CharField(max_length=200, null=True, help_text="Iqualys_category")
    Qualys_severity = models.CharField(max_length=200, null=True, help_text="qualys_severity")
    Qualys_group = models.CharField(max_length=200, null=True, help_text="qualys_group")
    Qualys_payload_method = models.CharField(max_length=200, null=True, help_text="qualys_payload_method")
    Qualys_payload_response = models.CharField(max_length=200, null=True, help_text="qualys_payload_response")
    Qualys_state = models.CharField(max_length=200, null=True, help_text="qualys_state")
    Qualys_owasp_name = models.CharField(max_length=200, null=True, help_text="qualys_owasp_name")
    Qualys_impact = models.CharField(max_length=200, null=True, help_text="Iqualys_impact")
    Qualys_owasp = models.CharField(max_length=200, null=True, help_text="qualys_owasp")
    Qualys_solution = models.CharField(max_length=200, null=True, help_text="qualys_solution")
    Qualys_cvss_base = models.CharField(max_length=200, null=True, help_text="qualys_cvss_base")
    Qualys_cvss_temporary = models.CharField(max_length=200, null=True, help_text="qualys_cvss_temporary")
    Qualys_id = models.CharField(max_length=200, null=True, help_text="qualys_id")
    Sensor = models.CharField(max_length=200, null=True, help_text="Sensor")
    ID = models.IntegerField(null=True, help_text="Id")
    Case_With_Manufacturer = models.CharField(max_length=200, null=True, help_text="Case_With_Manufacturer")
    Spare_Parts_Stock_Delivery_Date = models.CharField(max_length=200, null=True,
                                                       help_text="Spare_Parts_Stock_Delivery_Date")
    Onsite_engineer_request_date = models.CharField(max_length=200, null=True, help_text="Onsite_engineer_request_date")
    Onsite_care_date = models.CharField(max_length=200, null=True, help_text="Onsite_care_date")
    Onsite_service_SLA = models.CharField(max_length=200, null=True, help_text="Onsite_service_SLA")
    Neutralization_SLA = models.CharField(max_length=200, null=True, help_text="Neutralization_SLA")
    Fault_Neutralization_Date = models.CharField(max_length=200, null=True, help_text="Fault_Neutralization_Date")
    Telephone_notification_date = models.CharField(max_length=200, null=True, help_text="Telephone_notification_date")
    SLA_Service_time_for_remote_connection = models.CharField(max_length=200, null=True,
                                                              help_text="SLA_Service_time_for_remote_connection")
    SLA_Stock_of_Spare_Parts = models.CharField(max_length=200, null=True, help_text="SLA_Stock_of_Spare_Parts")
    Hardware_Damage_Confirmation_Date_Manufacturer = models.CharField(max_length=200, null=True,
                                                                      help_text="Hardware_Damage_Confirmation_Date")
    SLA_Spare_Parts_Stock_Delivery_Time = models.CharField(max_length=200, null=True,
                                                           help_text="SLA_Spare_Parts_Stock_Delivery_Time")
    Contract_start_date = models.CharField(max_length=200, null=True, help_text="Contract_start_date")
    Bill = models.CharField(max_length=200, null=True, help_text="Bill")
    Response_due_time = models.DateTimeField(null=True, help_text="Response Due Time")
    First_Responder_Status_Expired = models.BooleanField(null=True, help_text="First sponder status expired")
    Last_update_time = models.DateTimeField(null=True, help_text="Last_update_time")
    Resolution_time = models.DateTimeField(null=True, help_text="Resolution_time")
    VIP_user = models.BooleanField(null=True, help_text="VIP_user")
    SIEM_id = models.CharField(null=True, max_length=200, help_text="SIEM Id")
