# Generated by Django 4.0 on 2022-07-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_stage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='category_rule',
            field=models.CharField(help_text='category_rule', max_length=200, null=True, verbose_name='category_rule'),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='default',
            field=models.CharField(help_text='Default', max_length=200, verbose_name='default'),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='description',
            field=models.CharField(help_text='Description', max_length=200, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='ios_name',
            field=models.CharField(help_text='IOS Name', max_length=200, verbose_name='ios_name'),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='usecase',
            field=models.CharField(help_text='Use Case', max_length=200, verbose_name='use_case'),
        ),
    ]
