# Generated by Django 4.0 on 2022-07-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_stage', '0002_usecase_category_rule_alter_usecase_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usecase',
            name='default',
        ),
        migrations.AddField(
            model_name='usecase',
            name='correlation_rule',
            field=models.CharField(help_text='correlation rule', max_length=256, null=True, verbose_name='correlation_rule'),
        ),
        migrations.AddField(
            model_name='usecase',
            name='default_syntax',
            field=models.CharField(help_text='default syntax', max_length=200, null=True, verbose_name='default_syntax'),
        ),
        migrations.AddField(
            model_name='usecase',
            name='subcategory_rule',
            field=models.CharField(help_text='subcategory rule', max_length=256, null=True, verbose_name='subcategory_rule'),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='description',
            field=models.CharField(help_text='Description', max_length=200, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='ios_name',
            field=models.CharField(help_text='IOS Name', max_length=200, null=True, verbose_name='ios_name'),
        ),
    ]
