# Generated by Django 4.0 on 2022-07-26 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_stage', '0003_remove_usecase_default_usecase_correlation_rule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usecase',
            name='ios_name',
        ),
    ]
