# Generated by Django 4.0 on 2022-10-17 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_stage', '0004_remove_usecase_ios_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='default',
            field=models.CharField(help_text='Default', max_length=200, verbose_name='default'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='description',
            field=models.CharField(help_text='Description', max_length=200, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_name',
            field=models.CharField(help_text='Rule Name', max_length=200, verbose_name='rule_name'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='usecase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shared_stage.usecase', verbose_name='usecase'),
        ),
    ]
