# Generated by Django 4.0 on 2022-07-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsm',
            name='Fault_Neutralization_Date',
            field=models.CharField(help_text='Fault_Neutralization_Date', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Hardware_Damage_Confirmation_Date_Manufacturer',
            field=models.CharField(help_text='Hardware_Damage_Confirmation_Date', max_length=200, null=True),
        ),
    ]
