# Generated by Django 4.0 on 2022-08-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0004_remove_assets_category_assets_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sita',
            old_name='category',
            new_name='service_category',
        ),
        migrations.RenameField(
            model_name='sita',
            old_name='request_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='sita',
            name='last_update_time',
        ),
        migrations.RemoveField(
            model_name='sita',
            name='level',
        ),
        migrations.RemoveField(
            model_name='sita',
            name='ticket_details',
        ),
        migrations.RemoveField(
            model_name='sita',
            name='ticket_status',
        ),
        migrations.AddField(
            model_name='sita',
            name='Suspicious',
            field=models.CharField(help_text='suspicious', max_length=20000, null=True, verbose_name='Suspicious'),
        ),
        migrations.AddField(
            model_name='sita',
            name='assets',
            field=models.CharField(help_text='log source', max_length=20000, null=True, verbose_name='assets'),
        ),
        migrations.AddField(
            model_name='sita',
            name='assigned_time',
            field=models.CharField(help_text='Time send mail', max_length=200, null=True, verbose_name='assigned_time'),
        ),
        migrations.AddField(
            model_name='sita',
            name='due_by_time',
            field=models.CharField(help_text='DueBy Time', max_length=20000, null=True, verbose_name='due_by_time'),
        ),
        migrations.AddField(
            model_name='sita',
            name='first_response_due_by_time',
            field=models.CharField(help_text='First Response overdue status', max_length=20000, null=True, verbose_name='first_response_due_by_time'),
        ),
        migrations.AddField(
            model_name='sita',
            name='impact',
            field=models.CharField(help_text='impact', max_length=200, null=True, verbose_name='impact'),
        ),
        migrations.AddField(
            model_name='sita',
            name='is_first_response_overdue',
            field=models.CharField(help_text='Response DueBy Time', max_length=200, null=True, verbose_name='is_first_response_overdue'),
        ),
        migrations.AddField(
            model_name='sita',
            name='is_overdue',
            field=models.CharField(help_text='Overdue Status', max_length=200, null=True, verbose_name='is_overdue'),
        ),
        migrations.AddField(
            model_name='sita',
            name='replys',
            field=models.CharField(help_text='Replies', max_length=200, null=True, verbose_name='replys'),
        ),
        migrations.AddField(
            model_name='sita',
            name='resolution',
            field=models.CharField(help_text='resolution', max_length=200, null=True, verbose_name='resolution'),
        ),
        migrations.AddField(
            model_name='sita',
            name='site',
            field=models.CharField(help_text='location', max_length=200, null=True, verbose_name='site'),
        ),
        migrations.AddField(
            model_name='sita',
            name='urgency',
            field=models.CharField(help_text='urgency', max_length=20000, null=True, verbose_name='urgency'),
        ),
        migrations.AlterField(
            model_name='sita',
            name='created_time',
            field=models.CharField(help_text='created time', max_length=200, null=True, verbose_name='created_time'),
        ),
    ]
