# Generated by Django 4.0 on 2022-08-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0007_alter_hub_assigned_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsm',
            name='events',
            field=models.IntegerField(help_text='events', null=True, verbose_name='events'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Account',
            field=models.CharField(help_text='Account', max_length=200, null=True, verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Affair',
            field=models.CharField(help_text='Affair', max_length=200, verbose_name='Affair'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Answer_date',
            field=models.DateTimeField(help_text='Answer Date', max_length=200, null=True, verbose_name='Answer_date'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Applicant',
            field=models.CharField(help_text='Applicant', max_length=200, null=True, verbose_name='Applicant'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Application_Status',
            field=models.CharField(help_text='Application status', max_length=200, null=True, verbose_name='Application_Status'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Approval_Status',
            field=models.CharField(help_text='Approval Status', max_length=200, null=True, verbose_name='Approval_Status'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Article',
            field=models.CharField(help_text='Article', max_length=200, null=True, verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Asset_Name',
            field=models.CharField(help_text='Asset Name', max_length=200, null=True, verbose_name='Asset_Name'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Bill',
            field=models.CharField(help_text='Bill', max_length=200, null=True, verbose_name='Bill'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Case_With_Manufacturer',
            field=models.CharField(help_text='Case_With_Manufacturer', max_length=200, null=True, verbose_name='Case_With_Manufacturer'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Category',
            field=models.CharField(help_text='Category', max_length=200, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Cluster',
            field=models.CharField(help_text='Cluster', max_length=200, null=True, verbose_name='Cluster'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Complexity',
            field=models.CharField(help_text='Complexity', max_length=200, null=True, verbose_name='Complexity'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Contract_start_date',
            field=models.CharField(help_text='Contract_start_date', max_length=200, null=True, verbose_name='Contract_start_date'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='CreatedTime',
            field=models.DateTimeField(help_text='Created Time', max_length=200, null=True, verbose_name='CreatedTime'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Created_by',
            field=models.CharField(help_text='Created By', max_length=200, null=True, verbose_name='Created_by'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Department',
            field=models.CharField(help_text='Department', max_length=200, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Description',
            field=models.CharField(help_text='Description', max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Ending_time',
            field=models.DateTimeField(help_text='Ending Time', max_length=200, null=True, verbose_name='Ending_time'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Exchanged_Service',
            field=models.CharField(help_text='Exchanged_Service', max_length=200, null=True, verbose_name='Exchanged_Service'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Expiration_time',
            field=models.DateTimeField(help_text='Expiration Time', max_length=200, null=True, verbose_name='Expiration_time'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Expired_status',
            field=models.BooleanField(help_text='Expire Status', null=True, verbose_name='Expired_status'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Fault_Neutralization_Date',
            field=models.CharField(help_text='Fault_Neutralization_Date', max_length=200, null=True, verbose_name='Fault_Neutralization_Date'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='First_Responder_Status_Expired',
            field=models.BooleanField(help_text='First sponder status expired', null=True, verbose_name='First_Responder_Status_Expired'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Hardware_Damage_Confirmation_Date_Manufacturer',
            field=models.CharField(help_text='Hardware_Damage_Confirmation_Date', max_length=200, null=True, verbose_name='Hardware_Damage_Confirmation_Date_Manufacturer'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='ID',
            field=models.IntegerField(help_text='Id', null=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Impact',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], help_text='Impact', max_length=200, null=True, verbose_name='Impact'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Itsm_id',
            field=models.CharField(help_text='ITSM Id', max_length=200, null=True, verbose_name='Itsm_id'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Last_update_time',
            field=models.DateTimeField(help_text='Last_update_time', null=True, verbose_name='Last_update_time'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Level',
            field=models.CharField(help_text='Level', max_length=200, null=True, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Neutralization_SLA',
            field=models.CharField(help_text='Neutralization_SLA', max_length=200, null=True, verbose_name='Neutralization_SLA'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Number_of_Services',
            field=models.IntegerField(help_text='Number_of_Services', null=True, verbose_name='Number_of_Services'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Onsite_care_date',
            field=models.CharField(help_text='Onsite_care_date', max_length=200, null=True, verbose_name='Case_With_Manufacturer'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Onsite_engineer_request_date',
            field=models.CharField(help_text='Onsite_engineer_request_date', max_length=200, null=True, verbose_name='Case_With_Manufacturer'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Onsite_service_SLA',
            field=models.CharField(help_text='Onsite_service_SLA', max_length=200, null=True, verbose_name='Onsite_service_SLA'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Opportunity_Status',
            field=models.CharField(help_text='Opportunity_Status', max_length=200, null=True, verbose_name='Opportunity_Status'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Pending_status',
            field=models.BooleanField(help_text='Pending Status', null=True, verbose_name='Pending_status'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], help_text='Priority', max_length=200, null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Qualys_category',
            field=models.CharField(help_text='Iqualys_category', max_length=200, null=True, verbose_name='Qualys_category'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Qualys_cvss_base',
            field=models.CharField(help_text='qualys_cvss_base', max_length=200, null=True, verbose_name='Qualys_cvss_base'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Qualys_cvss_temporary',
            field=models.CharField(help_text='qualys_cvss_temporary', max_length=200, null=True, verbose_name='Qualys_cvss_temporary'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Qualys_first_time_detected',
            field=models.CharField(help_text='qualys_first_time_detected', max_length=200, null=True, verbose_name='Qualys_first_time_detected'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Qualys_group',
            field=models.CharField(help_text='qualys_group', max_length=200, null=True, verbose_name='Qualys_group'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Qualys_id',
            field=models.CharField(help_text='qualys_id', max_length=200, null=True, verbose_name='Qualys_id'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Qualys_impact',
            field=models.CharField(help_text='Iqualys_impact', max_length=200, null=True, verbose_name='Qualys_impact'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Qualys_last_time_detected',
            field=models.CharField(help_text='Iqualys_last_time_detected', max_length=200, null=True, verbose_name='Qualys_last_time_detected'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Qualys_last_time_tested',
            field=models.CharField(help_text='qualys_last_time_tested', max_length=200, null=True, verbose_name='Qualys_last_time_tested'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Qualys_owasp',
            field=models.CharField(help_text='qualys_owasp', max_length=200, null=True, verbose_name='Qualys_owasp'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Qualys_owasp_name',
            field=models.CharField(help_text='qualys_owasp_name', max_length=200, null=True, verbose_name='Qualys_owasp_name'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Qualys_payload_method',
            field=models.CharField(help_text='qualys_payload_method', max_length=200, null=True, verbose_name='Qualys_payload_method'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Qualys_payload_response',
            field=models.CharField(help_text='qualys_payload_response', max_length=200, null=True, verbose_name='Qualys_payload_response'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Qualys_severity',
            field=models.CharField(help_text='qualys_severity', max_length=200, null=True, verbose_name='Qualys_severity'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Qualys_solution',
            field=models.CharField(help_text='qualys_solution', max_length=200, null=True, verbose_name='Qualys_solution'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Qualys_state',
            field=models.CharField(help_text='qualys_state', max_length=200, null=True, verbose_name='Qualys_state'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Qualys_url',
            field=models.CharField(help_text='qualys_url', max_length=200, null=True, verbose_name='Qualys_url'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='RCF',
            field=models.BooleanField(help_text='RCF', null=True, verbose_name='RCF'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Region',
            field=models.CharField(help_text='Region', max_length=200, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Reopened',
            field=models.BooleanField(help_text='Reopened', null=True, verbose_name='Reopened'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='RequestID',
            field=models.CharField(help_text='Request Id', max_length=200, null=True, verbose_name='RequestID'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='RequestStatus',
            field=models.CharField(help_text='Request Status', max_length=200, null=True, verbose_name='RequestStatus'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='RequestType',
            field=models.CharField(help_text='Request Type', max_length=200, null=True, verbose_name='RequestType'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Request_Closure_Comments',
            field=models.CharField(help_text='Request_Closure_Comments', max_length=200, null=True, verbose_name='Request_Closure_Comments'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Request_closing_code',
            field=models.CharField(help_text='Request Closing Code', max_length=200, null=True, verbose_name='Request_closing_code'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Request_mode',
            field=models.CharField(choices=[('Email', 'Email'), ('Call', 'Call'), ('Message', 'Message'), ('Whatsapp', 'Whatsapp')], help_text='Request Mode', max_length=200, null=True, verbose_name='Request_mode'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Resolution',
            field=models.CharField(help_text='Resolution', max_length=200, null=True, verbose_name='Resolution'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Resolution_time',
            field=models.DateTimeField(help_text='Resolution_time', null=True, verbose_name='Resolution_time'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Response_due_time',
            field=models.DateTimeField(help_text='Response Due Time', null=True, verbose_name='Response_due_time'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='SIEM_id',
            field=models.CharField(help_text='SIEM Id', max_length=200, null=True, verbose_name='SIEM_id'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='SLA_Service_time_for_remote_connection',
            field=models.CharField(help_text='SLA_Service_time_for_remote_connection', max_length=200, null=True, verbose_name='SLA_Service_time_for_remote_connection'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='SLA_Spare_Parts_Stock_Delivery_Time',
            field=models.CharField(help_text='SLA_Spare_Parts_Stock_Delivery_Time', max_length=200, null=True, verbose_name='SLA_Spare_Parts_Stock_Delivery_Time'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='SLA_Stock_of_Spare_Parts',
            field=models.CharField(help_text='SLA_Stock_of_Spare_Parts', max_length=200, null=True, verbose_name='SLA_Stock_of_Spare_Parts'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Sale_order',
            field=models.CharField(help_text='Sale_order', max_length=200, null=True, verbose_name='Sale_order'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Sensor',
            field=models.CharField(help_text='Sensor', max_length=200, null=True, verbose_name='Sensor'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='ServiceCategory',
            field=models.CharField(help_text='Service Category', max_length=200, null=True, verbose_name='ServiceCategory'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Site',
            field=models.CharField(help_text='Site', max_length=200, null=True, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Solicitant_area',
            field=models.CharField(help_text='Solicitant_area', max_length=200, null=True, verbose_name='Solicitant_area'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Spare_Parts_Stock_Delivery_Date',
            field=models.CharField(help_text='Spare_Parts_Stock_Delivery_Date', max_length=200, null=True, verbose_name='Spare_Parts_Stock_Delivery_Date'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Subcategory',
            field=models.CharField(help_text='Sub Category', max_length=200, null=True, verbose_name='Subcategory'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Subject',
            field=models.CharField(help_text='Subject', max_length=200, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Technician',
            field=models.CharField(help_text='Technician', max_length=200, null=True, verbose_name='Technician'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Telephone_notification_date',
            field=models.CharField(help_text='Telephone_notification_date', max_length=200, null=True, verbose_name='Telephone_notification_date'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Time_elapsed',
            field=models.DateTimeField(help_text='Time Elapsed', max_length=200, null=True, verbose_name='Time_elapsed'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Total_cost',
            field=models.CharField(help_text='Total_cost', max_length=200, null=True, verbose_name='Total_cost'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Type',
            field=models.CharField(help_text='Type', max_length=200, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Urgency',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], help_text='Urgency', max_length=200, null=True, verbose_name='Urgency'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='User_On_Behalf_Of_OBO',
            field=models.CharField(help_text='User_On_Behalf_Of_OBO', max_length=200, null=True, verbose_name='User_On_Behalf_Of_OBO'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='VIP_user',
            field=models.BooleanField(help_text='VIP_user', null=True, verbose_name='VIP_user'),
        ),
    ]
