# Generated by Django 4.0 on 2022-08-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0008_itsm_events_alter_itsm_account_alter_itsm_affair_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itsm',
            name='ServiceCategory',
        ),
        migrations.AddField(
            model_name='itsm',
            name='service_category',
            field=models.CharField(help_text='Service Category', max_length=200, null=True, verbose_name='service_category'),
        ),
        migrations.AddField(
            model_name='itsm',
            name='sla_name',
            field=models.CharField(help_text='sla_name', max_length=200, null=True, verbose_name='sla_name'),
        ),
    ]
