# Generated by Django 4.0 on 2022-08-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0020_itsm_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsm',
            name='location_name',
            field=models.CharField(default=2, help_text='location name', max_length=200, verbose_name='location_name'),
            preserve_default=False,
        ),
    ]
