# Generated by Django 4.0 on 2022-08-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0025_itsm_assigned_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsm',
            name='SLA_Spare_Parts_Stock_Delivery_Time',
            field=models.DateTimeField(help_text='SLA_Spare_Parts_Stock_Delivery_Time', null=True, verbose_name='SLA_Spare_Parts_Stock_Delivery_Time'),
        ),
    ]
