# Generated by Django 4.0 on 2022-08-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0031_itsm_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='sita',
            name='comments',
            field=models.CharField(help_text='comment for tickets', max_length=200, null=True, verbose_name='comments'),
        ),
    ]
