# Generated by Django 4.0 on 2022-08-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0032_hub_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsm',
            name='first_response_time',
            field=models.CharField(help_text='first_response_time', max_length=200, null=True, verbose_name='first_response_time'),
        ),
    ]
