# Generated by Django 4.0 on 2022-08-27 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0033_itsm_first_response_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(help_text='assigned user', max_length=200, verbose_name='assign_user')),
                ('selectedIncidents', models.OneToOneField(help_text='incident_id', on_delete=django.db.models.deletion.CASCADE, to='sita.sita')),
            ],
        ),
    ]
