# Generated by Django 4.0 on 2022-08-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0034_assigntask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigntask',
            name='selectedIncidents',
            field=models.CharField(help_text='assigned user', max_length=200, unique=True, verbose_name='assign_user'),
        ),
    ]
