# Generated by Django 4.0 on 2022-09-22 09:23

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0037_alter_itsm_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='siem',
            name='target',
            field=models.CharField(help_text='target', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='soar',
            name='AlertsCount',
            field=models.CharField(help_text='alertscount', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sita',
            name='asset_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='asset color', image_field=None, max_length=18, null=True, samples=None, verbose_name='asset_color'),
        ),
        migrations.AlterField(
            model_name='sita',
            name='asset_name',
            field=models.CharField(help_text='asset name', max_length=200, null=True, verbose_name='asset_name'),
        ),
        migrations.AlterField(
            model_name='sita',
            name='asset_type',
            field=models.CharField(help_text='asset type', max_length=200, null=True, verbose_name='asset_type'),
        ),
        migrations.AlterField(
            model_name='sita',
            name='description',
            field=models.CharField(help_text='description', max_length=2000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='sita',
            name='entity_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='entity color', image_field=None, max_length=18, null=True, samples=None, verbose_name='entity_color'),
        ),
        migrations.AlterField(
            model_name='sita',
            name='entity_name',
            field=models.CharField(help_text='entity name', max_length=200, null=True, verbose_name='entity_name'),
        ),
        migrations.AlterField(
            model_name='sita',
            name='function_name',
            field=models.CharField(help_text='function name', max_length=200, null=True, verbose_name='function_name'),
        ),
        migrations.AlterField(
            model_name='sita',
            name='location_name',
            field=models.CharField(help_text='location name', max_length=200, null=True, verbose_name='location_name'),
        ),
        migrations.AlterField(
            model_name='sita',
            name='resolution',
            field=models.CharField(help_text='resolution', max_length=10000, null=True, verbose_name='resolution'),
        ),
        migrations.AlterField(
            model_name='sita',
            name='rule_name',
            field=models.CharField(help_text='rule name', max_length=200, null=True, verbose_name='rule_name'),
        ),
        migrations.AlterField(
            model_name='sita',
            name='use_case',
            field=models.CharField(help_text='use case', max_length=200, null=True, verbose_name='use_case'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Affair',
            field=models.CharField(help_text='Affair', max_length=200, null=True, verbose_name='Affair'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Description',
            field=models.CharField(help_text='Description', max_length=15000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Exchanged_Service',
            field=models.CharField(help_text='Exchanged_Service', max_length=2000, null=True, verbose_name='Exchanged_Service'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='RCF',
            field=models.CharField(help_text='RCF', max_length=200, null=True, verbose_name='RCF'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Resolution',
            field=models.CharField(help_text='Resolution', max_length=10000, null=True, verbose_name='Resolution'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Technician',
            field=models.CharField(help_text='Technician', max_length=2000, null=True, verbose_name='Technician'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Time_elapsed',
            field=models.CharField(help_text='Time Elapsed', max_length=200, null=True, verbose_name='Time_elapsed'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='reopened',
            field=models.CharField(help_text='Reopened', max_length=2000, null=True, verbose_name='Reopened'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='closing_user',
            field=models.CharField(help_text='Closing User', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='siem',
            name='description',
            field=models.CharField(help_text='Description', max_length=2000, null=True, verbose_name='description'),
        ),
    ]
