# Generated by Django 4.0 on 2022-08-01 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_rename_insights_hub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='Category',
        ),
        migrations.AddField(
            model_name='assets',
            name='category',
            field=models.ForeignKey(default=1, help_text='Asset Category', on_delete=django.db.models.deletion.CASCADE, to='hub.category'),
            preserve_default=False,
        ),
    ]
