# Generated by Django 4.0 on 2022-08-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_rename_category_hub_service_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='subject',
            field=models.CharField(help_text='subject', max_length=256, null=True, verbose_name='subject'),
        ),
    ]
