# Generated by Django 4.0 on 2022-08-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_hub_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='assigned_time',
            field=models.DateTimeField(help_text='Time send mail', max_length=200, null=True, verbose_name='assigned_time'),
        ),
    ]
