# Generated by Django 4.0 on 2022-08-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_remove_itsm_servicecategory_itsm_service_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsm',
            name='is_overdue',
            field=models.BooleanField(help_text='Overdue Status', null=True, verbose_name='is_overdue'),
        ),
    ]
