# Generated by Django 4.0 on 2022-08-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0011_alter_itsm_is_overdue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='AssetType',
        ),
        migrations.AlterField(
            model_name='assets',
            name='criticality',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Critical', 'Critical')], default='Low', help_text='Criticality', max_length=100, verbose_name='criticality'),
        ),
    ]
