# Generated by Django 4.0 on 2022-08-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0013_itsm_sla_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsm',
            name='sla_id',
            field=models.CharField(help_text='sla_id', max_length=200, null=True, verbose_name='sla_id'),
        ),
    ]
