# Generated by Django 4.0 on 2022-08-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0019_rename_sla_id_itsm_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsm',
            name='submitted_by',
            field=models.CharField(help_text='submmited by', max_length=200, null=True, verbose_name='submitted_by'),
        ),
    ]
