# Generated by Django 4.0 on 2022-08-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0021_itsm_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsm',
            name='location_name',
            field=models.CharField(help_text='location name', max_length=200, null=True, verbose_name='location_name'),
        ),
    ]
