# Generated by Django 4.0 on 2022-08-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0022_alter_itsm_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsm',
            name='reply',
            field=models.CharField(help_text='Replies', max_length=200, null=True, verbose_name='replys'),
        ),
    ]
