# Generated by Django 4.0 on 2022-08-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0026_alter_itsm_sla_spare_parts_stock_delivery_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itsm',
            name='events',
        ),
        migrations.AddField(
            model_name='itsm',
            name='sla_completion_time',
            field=models.CharField(help_text='sla_completion_time', max_length=200, null=True, verbose_name='sla_completion_time'),
        ),
    ]
