# Generated by Django 4.0 on 2022-10-17 10:34

import colorfield.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0027_remove_itsm_events_itsm_sla_completion_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(help_text='incident_id', max_length=200, verbose_name='incident_id')),
                ('comment', models.CharField(help_text='comment', max_length=200, verbose_name='comment')),
                ('created', models.DateField(auto_now_add=True, help_text='created', null=True, verbose_name='created')),
            ],
        ),
        migrations.CreateModel(
            name='AddOeiComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(help_text='ticket_id', max_length=200, verbose_name='ticket_id')),
                ('comment', models.CharField(help_text='comment', max_length=200, verbose_name='comment')),
                ('created', models.DateField(auto_now_add=True, help_text='created', null=True, verbose_name='created')),
            ],
        ),
        migrations.CreateModel(
            name='AssignTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(help_text='incident_id', max_length=200, null=True, unique=True, verbose_name='incident_id')),
                ('assigned_user', models.CharField(help_text='assign_user', max_length=200, null=True, verbose_name='assign_user')),
                ('created', models.DateField(auto_now_add=True, help_text='created', null=True, verbose_name='created')),
            ],
        ),
        migrations.CreateModel(
            name='CyFeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.CharField(help_text='feed_id', max_length=200, null=True, verbose_name='feed_id')),
                ('feed_ref_id', models.CharField(help_text='feed_ref_id', max_length=200, null=True, verbose_name='feed_ref_id')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='timestamp', null=True, verbose_name='timestamp')),
                ('title', models.CharField(help_text='title', max_length=200, null=True, verbose_name='title')),
                ('descriptions', models.CharField(help_text='descriptions', max_length=1000, null=True, verbose_name='descriptions')),
                ('shortDescriptions', models.CharField(help_text='shortDescriptions', max_length=200, null=True, verbose_name='shortDescriptions')),
                ('vulnerabilities', models.CharField(help_text='vulnerabilities', max_length=500, null=True, verbose_name='vulnerabilities')),
                ('weaknesses', models.CharField(help_text='weaknesses', max_length=200, null=True, verbose_name='weaknesses')),
                ('configurations', models.CharField(help_text='configurations', max_length=200, null=True, verbose_name='configurations')),
                ('potentialCOAs', models.CharField(help_text='potentialCOAs', max_length=200, null=True, verbose_name='potentialCOAs')),
                ('handling', models.CharField(help_text='handling', max_length=200, null=True, verbose_name='handling')),
                ('relatedExploitTargets', models.CharField(help_text='relatedExploitTargets', max_length=200, null=True, verbose_name='relatedExploitTargets')),
                ('relatedPackages', models.CharField(help_text='relatedPackages', max_length=200, null=True, verbose_name='relatedPackages')),
                ('version', models.CharField(help_text='version', max_length=200, null=True, verbose_name='version')),
                ('informationSource_descriptions', models.CharField(help_text='informationSource_descriptions', max_length=200, null=True, verbose_name='informationSource_descriptions')),
                ('informationSource_identity', models.CharField(help_text='informationSource_identity', max_length=200, null=True, verbose_name='informationSource_identity')),
                ('informationSource_roles', models.CharField(help_text='informationSource_roles', max_length=200, null=True, verbose_name='informationSource_roles')),
                ('informationSource_contributingSources', models.CharField(help_text='informationSource_contributingSources', max_length=200, null=True, verbose_name='informationSource_contributingSources')),
                ('informationSource_time', models.DateTimeField(help_text='informationSource_time', null=True, verbose_name='informationSource_time')),
                ('informationSource_tools', models.CharField(help_text='informationSource_tools', max_length=200, null=True, verbose_name='informationSource_tools')),
                ('informationSource_references_references', models.CharField(help_text='informationSource_references_references', max_length=200, null=True, verbose_name='informationSource_references_references')),
            ],
        ),
        migrations.CreateModel(
            name='HubUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soar_id', models.CharField(help_text='soar_id', max_length=100, verbose_name='soar_id')),
                ('updates', models.CharField(help_text='updates', max_length=200, verbose_name='updates')),
                ('update_date', models.DateTimeField(auto_now_add=True, help_text='update_date', verbose_name='update_date')),
                ('updated_by', models.CharField(help_text='updated_by', max_length=100, verbose_name='updated_by')),
            ],
        ),
        migrations.CreateModel(
            name='Perspective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perspective_type', models.CharField(choices=[('Incident', 'Incident'), ('Pattern', 'Pattern')], help_text='perspective type', max_length=100, verbose_name='perspective type')),
                ('action_type', models.CharField(choices=[('notified', 'notified'), ('under_investigation', 'under_investigation'), ('contained', 'contained'), ('closed_by_etek', 'closed_by_etek'), ('closed_by_client', 'closed_by_client'), ('no_action', 'no_action')], help_text='action type', max_length=100, verbose_name='action type')),
                ('status_type', models.CharField(choices=[('confirmed', 'confirmed'), ('under_investigation', 'under_investigation'), ('false_positive', 'false_positive')], help_text='status type', max_length=100, verbose_name='status type')),
                ('criticality_type', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], help_text='perspective type', max_length=100, verbose_name='perspective type')),
                ('incident_id', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), default=list, help_text='incident_id', size=None, verbose_name='incident_id')),
                ('perspective_title', models.CharField(help_text='perspective_title', max_length=100, null=True, verbose_name='perspective_title')),
                ('perspective', models.TextField(help_text='perspective', null=True, verbose_name='perspective')),
                ('recommendation', models.TextField(help_text='recommendation', null=True, verbose_name='recommendation')),
                ('publish', models.BooleanField(default=False, help_text='publish', verbose_name='publish')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, help_text='Email Ids', size=None, verbose_name='emails'), null=True, size=None)),
                ('donut_left_graph', models.FileField(help_text='donut left graph', null=True, upload_to='perspective/donut_graph', verbose_name='donut left graph')),
                ('donut_right_graph', models.ImageField(help_text='donut left graph', null=True, upload_to='perspective/donut_graph', verbose_name='donut left graph')),
                ('comparative_left_graph', models.ImageField(help_text='donut left graph', null=True, upload_to='perspective/comparative_graph', verbose_name='donut left graph')),
                ('comparative_right_graph', models.ImageField(help_text='donut left graph', null=True, upload_to='perspective/comparative_graph', verbose_name='donut left graph')),
                ('incident_start_date_time', models.DateTimeField(help_text='incident_start_date_time', null=True, verbose_name='incident_start_date_time')),
                ('incident_end_date_time', models.DateTimeField(help_text='incident_end_date_time', null=True, verbose_name='incident_end_date_time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
        migrations.RenameField(
            model_name='itsm',
            old_name='Total_cost',
            new_name='total_cost',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='function_id',
        ),
        migrations.RemoveField(
            model_name='itsm',
            name='Number_of_Services',
        ),
        migrations.RemoveField(
            model_name='itsm',
            name='Reopened',
        ),
        migrations.AddField(
            model_name='assets',
            name='end_date',
            field=models.DateField(help_text='Delete Date', null=True, verbose_name='end_date'),
        ),
        migrations.AddField(
            model_name='assets',
            name='process_id',
            field=models.ForeignKey(default=1, help_text='Process Name', on_delete=django.db.models.deletion.CASCADE, to='hub.process', verbose_name='process_id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='end_date',
            field=models.DateField(help_text='Delete Date', null=True, verbose_name='end_date'),
        ),
        migrations.AddField(
            model_name='entity',
            name='end_date',
            field=models.DateField(help_text='Delete Date', null=True, verbose_name='end_date'),
        ),
        migrations.AddField(
            model_name='function',
            name='end_date',
            field=models.DateField(help_text='Delete Date', null=True, verbose_name='end_date'),
        ),
        migrations.AddField(
            model_name='geolocation',
            name='end_date',
            field=models.DateField(help_text='Delete Date', null=True, verbose_name='end_date'),
        ),
        migrations.AddField(
            model_name='hub',
            name='last_updated_datetime',
            field=models.DateTimeField(help_text='last_updated_time', max_length=200, null=True, verbose_name='last_updated_time'),
        ),
        migrations.AddField(
            model_name='hub',
            name='target',
            field=models.CharField(help_text='target', max_length=200, null=True, verbose_name='target_ip'),
        ),
        migrations.AddField(
            model_name='itsm',
            name='SOAR_ID',
            field=models.CharField(help_text='soar_id', max_length=200, null=True, verbose_name='Soar_id'),
        ),
        migrations.AddField(
            model_name='itsm',
            name='due_by_time',
            field=models.CharField(help_text='Due_by_Time', max_length=200, null=True, verbose_name='Due_by_Time'),
        ),
        migrations.AddField(
            model_name='itsm',
            name='false_positives',
            field=models.CharField(help_text='false_positives', max_length=200, null=True, verbose_name='false_positives'),
        ),
        migrations.AddField(
            model_name='itsm',
            name='false_positives_id',
            field=models.CharField(help_text='false_positives_id', max_length=200, null=True, verbose_name='false_positives_id'),
        ),
        migrations.AddField(
            model_name='itsm',
            name='first_response_time',
            field=models.CharField(help_text='first_response_time', max_length=200, null=True, verbose_name='first_response_time'),
        ),
        migrations.AddField(
            model_name='itsm',
            name='first_response_time_id',
            field=models.CharField(help_text='first_response_time_id', max_length=200, null=True, verbose_name='first_response_time_id'),
        ),
        migrations.AddField(
            model_name='itsm',
            name='group',
            field=models.CharField(help_text='group', max_length=200, null=True, verbose_name='group'),
        ),
        migrations.AddField(
            model_name='itsm',
            name='is_first_response_overdue',
            field=models.CharField(help_text='Is_First_Response_Overdue', max_length=200, null=True, verbose_name='Is_First_Respose_Overdue'),
        ),
        migrations.AddField(
            model_name='itsm',
            name='number_of_services',
            field=models.CharField(help_text='Number_of_Services', max_length=200, null=True, verbose_name='Number_of_Services'),
        ),
        migrations.AddField(
            model_name='itsm',
            name='reopened',
            field=models.CharField(help_text='Reopened', max_length=2000, null=True, verbose_name='Reopened'),
        ),
        migrations.AddField(
            model_name='itsm',
            name='reopened_id',
            field=models.CharField(help_text='reopened_id', max_length=200, null=True, verbose_name='reopened_id'),
        ),
        migrations.AddField(
            model_name='itsm',
            name='resolved_time',
            field=models.CharField(help_text='resolved_time', max_length=200, null=True, verbose_name='resolved_time'),
        ),
        migrations.AddField(
            model_name='itsm',
            name='response_time',
            field=models.CharField(help_text='response_time', max_length=200, null=True, verbose_name='reesponse_time'),
        ),
        migrations.AddField(
            model_name='itsm',
            name='response_time_id',
            field=models.CharField(help_text='response_time_id', max_length=200, null=True, verbose_name='response_time_id'),
        ),
        migrations.AddField(
            model_name='itsm',
            name='target',
            field=models.CharField(help_text='Target', max_length=200, null=True, verbose_name='target'),
        ),
        migrations.AddField(
            model_name='process',
            name='end_date',
            field=models.DateField(help_text='Delete Date', null=True, verbose_name='end_date'),
        ),
        migrations.AddField(
            model_name='process',
            name='function_id',
            field=models.ForeignKey(default=1, help_text='Function Name', on_delete=django.db.models.deletion.CASCADE, to='hub.function', verbose_name='function_id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siem',
            name='target',
            field=models.CharField(help_text='target', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='soar',
            name='AlertsCount',
            field=models.CharField(help_text='alertscount', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hub',
            name='asset_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='asset color', image_field=None, max_length=18, null=True, samples=None, verbose_name='asset_color'),
        ),
        migrations.AlterField(
            model_name='hub',
            name='asset_name',
            field=models.CharField(help_text='asset name', max_length=200, null=True, verbose_name='asset_name'),
        ),
        migrations.AlterField(
            model_name='hub',
            name='asset_type',
            field=models.CharField(help_text='asset type', max_length=200, null=True, verbose_name='asset_type'),
        ),
        migrations.AlterField(
            model_name='hub',
            name='description',
            field=models.CharField(help_text='description', max_length=2000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='hub',
            name='entity_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='entity color', image_field=None, max_length=18, null=True, samples=None, verbose_name='entity_color'),
        ),
        migrations.AlterField(
            model_name='hub',
            name='entity_name',
            field=models.CharField(help_text='entity name', max_length=200, null=True, verbose_name='entity_name'),
        ),
        migrations.AlterField(
            model_name='hub',
            name='function_name',
            field=models.CharField(help_text='function name', max_length=200, null=True, verbose_name='function_name'),
        ),
        migrations.AlterField(
            model_name='hub',
            name='location_name',
            field=models.CharField(help_text='location name', max_length=200, null=True, verbose_name='location_name'),
        ),
        migrations.AlterField(
            model_name='hub',
            name='resolution',
            field=models.CharField(help_text='resolution', max_length=10000, null=True, verbose_name='resolution'),
        ),
        migrations.AlterField(
            model_name='hub',
            name='rule_name',
            field=models.CharField(help_text='rule name', max_length=200, null=True, verbose_name='rule_name'),
        ),
        migrations.AlterField(
            model_name='hub',
            name='use_case',
            field=models.CharField(help_text='use case', max_length=200, null=True, verbose_name='use_case'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Affair',
            field=models.CharField(help_text='Affair', max_length=200, null=True, verbose_name='Affair'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Description',
            field=models.CharField(help_text='Description', max_length=15000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Exchanged_Service',
            field=models.CharField(help_text='Exchanged_Service', max_length=2000, null=True, verbose_name='Exchanged_Service'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='RCF',
            field=models.CharField(help_text='RCF', max_length=200, null=True, verbose_name='RCF'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Resolution',
            field=models.CharField(help_text='Resolution', max_length=10000, null=True, verbose_name='Resolution'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Technician',
            field=models.CharField(help_text='Technician', max_length=2000, null=True, verbose_name='Technician'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='Time_elapsed',
            field=models.CharField(help_text='Time Elapsed', max_length=200, null=True, verbose_name='Time_elapsed'),
        ),
        migrations.AlterField(
            model_name='process',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='process',
            name='process',
            field=models.CharField(help_text='Process Name', max_length=50, null=True, verbose_name='process'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='assigned_to',
            field=models.IntegerField(help_text='Assigned To', null=True, verbose_name='assigned_to'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='categories',
            field=models.CharField(help_text='Categories', max_length=200, null=True, verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='category_count',
            field=models.IntegerField(help_text='Category Count', null=True, verbose_name='category_count'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='close_time',
            field=models.DateTimeField(help_text='Close Time', max_length=200, null=True, verbose_name='close_time'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='closing_reason_id',
            field=models.IntegerField(help_text='Closing Reason id', null=True, verbose_name='closing_reason_id'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='closing_user',
            field=models.CharField(help_text='Closing User', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='siem',
            name='credibility',
            field=models.IntegerField(help_text='Credibility', null=True, verbose_name='credibility'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='description',
            field=models.CharField(help_text='Description', max_length=2000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='destination_networks',
            field=models.CharField(help_text='Destination Network', max_length=200, null=True, verbose_name='destination_networks'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='device_count',
            field=models.IntegerField(help_text='Device Count', null=True, verbose_name='device_count'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='domain_id',
            field=models.IntegerField(help_text='Domain Id', null=True, verbose_name='domain_id'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='event_count',
            field=models.IntegerField(help_text='Event Count', null=True, verbose_name='event_count'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='flow_count',
            field=models.IntegerField(help_text='Flow Count', null=True, verbose_name='flow_count'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='follow_up',
            field=models.BooleanField(help_text='Follow Up', null=True, verbose_name='follow_up'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='inactive',
            field=models.BooleanField(help_text='Inactive', null=True, verbose_name='inactive'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='last_updated_datetime',
            field=models.DateTimeField(help_text='Last Updated Date Time', max_length=200, null=True, verbose_name='last_updated_datetime'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='local_destination_address_ids',
            field=models.CharField(help_text='Local destination address ids', max_length=200, null=True, verbose_name='local_destination_address_ids'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='local_destination_count',
            field=models.IntegerField(help_text='Local Destination Count', null=True, verbose_name='local_destination_count'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='log_sources',
            field=models.CharField(help_text='Log Sources', max_length=200, null=True, verbose_name='log_sources'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='magnitude',
            field=models.IntegerField(help_text='Magnitude', null=True, verbose_name='magnitude'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='offense_source',
            field=models.CharField(help_text='Offense Source', max_length=200, null=True, verbose_name='offense_source'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='offense_type',
            field=models.IntegerField(help_text='Offense Type', null=True, verbose_name='offense_type'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='policy_category_count',
            field=models.IntegerField(help_text='Policy category Count', null=True, verbose_name='policy_category_count'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='protected',
            field=models.BooleanField(help_text='Protected', null=True, verbose_name='protected'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='relevance',
            field=models.IntegerField(help_text='Relevance', null=True, verbose_name='relevance'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='remote_destination_count',
            field=models.IntegerField(help_text='Remote Destination Count', null=True, verbose_name='remote_destination_count'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='rule_name',
            field=models.CharField(help_text='Rule Name', max_length=200, null=True, verbose_name='rule_name'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='rules',
            field=models.CharField(help_text='Rules', max_length=200, null=True, verbose_name='rules'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='security_category_count',
            field=models.IntegerField(help_text='Security Category Count', null=True, verbose_name='security_category_count'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='seim_id',
            field=models.IntegerField(help_text='SIEM Id', verbose_name='seim_id'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='severity',
            field=models.IntegerField(help_text='Severity', null=True, verbose_name='severity'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='source_address_ids',
            field=models.CharField(help_text='Source address ids', max_length=200, null=True, verbose_name='source_address_ids'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='source_count',
            field=models.IntegerField(help_text='Source Count', null=True, verbose_name='source_count'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='source_network',
            field=models.CharField(help_text='Source Network', max_length=200, null=True, verbose_name='source_network'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='start_datetime',
            field=models.DateTimeField(help_text='Start Date Time', max_length=200, null=True, verbose_name='start_datetime'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='status',
            field=models.CharField(help_text='Status', max_length=200, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='siem',
            name='username_count',
            field=models.IntegerField(help_text='Username Count', null=True, verbose_name='username_count'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='AssignedUser',
            field=models.CharField(help_text='Assigned User', max_length=200, null=True, verbose_name='AssignedUser'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='Case_id',
            field=models.CharField(help_text='Case Id', max_length=200, null=True, verbose_name='Case_id'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='ClosingTime',
            field=models.DateTimeField(help_text='Closing Time', max_length=200, null=True, verbose_name='ClosingTime'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='Environment',
            field=models.CharField(help_text='Environment', max_length=200, null=True, verbose_name='Environment'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='Important',
            field=models.BooleanField(help_text='Important', null=True, verbose_name='Important'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='Incident',
            field=models.BooleanField(help_text='Incident', null=True, verbose_name='Incident'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='Outcomes',
            field=models.CharField(help_text='Outcomes', max_length=200, null=True, verbose_name='Outcomes'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='Ports',
            field=models.IntegerField(help_text='Ports', null=True, verbose_name='Ports'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='Priority',
            field=models.CharField(help_text='Priority', max_length=200, null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='Products',
            field=models.CharField(help_text='Product', max_length=200, null=True, verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='Reason',
            field=models.CharField(help_text='Reason', max_length=200, null=True, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='RootCause',
            field=models.CharField(help_text='Root Cause', max_length=200, null=True, verbose_name='RootCause'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='SOAR_ID',
            field=models.IntegerField(help_text='SOAR Id', null=True, verbose_name='SOAR_ID'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='Sources',
            field=models.CharField(help_text='Sources', max_length=200, null=True, verbose_name='Sources'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='Stage',
            field=models.CharField(help_text='Stage', max_length=200, null=True, verbose_name='Stage'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='Status',
            field=models.CharField(help_text='Status', max_length=200, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='Suspicious',
            field=models.BooleanField(help_text='Suspicious', null=True, verbose_name='Suspicious'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='Tags',
            field=models.CharField(help_text='Tags', max_length=200, null=True, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='TicketIDs',
            field=models.CharField(help_text='Ticket Ids', max_length=200, verbose_name='TicketIDs'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='Time',
            field=models.DateTimeField(help_text='Time', max_length=200, null=True, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='soar',
            name='Title',
            field=models.CharField(help_text='Title', max_length=200, null=True, verbose_name='Title'),
        ),
    ]
