# Generated by Django 4.0 on 2022-08-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0027_remove_itsm_events_itsm_sla_completion_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsm',
            name='false_positives_id',
            field=models.CharField(help_text='false_positives_id', max_length=200, null=True, verbose_name='false_positives_id'),
        ),
        migrations.AddField(
            model_name='itsm',
            name='first_response_time_id',
            field=models.CharField(help_text='first_response_time_id', max_length=200, null=True, verbose_name='first_response_time_id'),
        ),
        migrations.AddField(
            model_name='itsm',
            name='reopened_id',
            field=models.CharField(help_text='reopened_id', max_length=200, null=True, verbose_name='reopened_id'),
        ),
        migrations.AddField(
            model_name='itsm',
            name='response_time_id',
            field=models.CharField(help_text='response_time_id', max_length=200, null=True, verbose_name='response_time_id'),
        ),
    ]
