# Generated by Django 4.0 on 2022-08-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0027_remove_itsm_events_itsm_sla_completion_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itsm',
            old_name='Number_of_Services',
            new_name='number_of_services',
        ),
        migrations.RenameField(
            model_name='itsm',
            old_name='Total_cost',
            new_name='total_cost',
        ),
    ]
