# Generated by Django 4.0 on 2022-10-17 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0028_addcomment_addoeicomment_assigntask_cyfeeds_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perspective',
            name='created_by',
            field=models.ForeignKey(db_index=False, help_text='Created by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.user', verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='perspective',
            name='updated_by',
            field=models.ForeignKey(db_index=False, help_text='Updated by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.user', verbose_name='Updated by'),
        ),
    ]
