# Generated by Django 4.0 on 2022-08-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0028_rename_number_of_services_itsm_number_of_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsm',
            name='false_positives_id',
            field=models.CharField(help_text='false_positives_id', max_length=200, null=True, verbose_name='false_positives_id'),
        ),
        migrations.AddField(
            model_name='itsm',
            name='first_response_time_id',
            field=models.CharField(help_text='first_response_time_id', max_length=200, null=True, verbose_name='first_response_time_id'),
        ),
        migrations.AddField(
            model_name='itsm',
            name='reopened_id',
            field=models.CharField(help_text='reopened_id', max_length=200, null=True, verbose_name='reopened_id'),
        ),
        migrations.AddField(
            model_name='itsm',
            name='response_time_id',
            field=models.CharField(help_text='response_time_id', max_length=200, null=True, verbose_name='response_time_id'),
        ),
        migrations.AlterField(
            model_name='itsm',
            name='number_of_services',
            field=models.CharField(help_text='Number_of_Services', max_length=200, null=True, verbose_name='Number_of_Services'),
        ),
    ]
