# Generated by Django 4.0 on 2022-08-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0030_remove_itsm_reopened_itsm_false_positives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsm',
            name='comments',
            field=models.CharField(help_text='comment for tickets', max_length=200, null=True, verbose_name='comments'),
        ),
    ]
